### ISSUE TITLE
Option to enable/disable logging

### ISSUE THREAD

**Issue by andre1974** [iobroker-community-adapters/ioBroker.sourceanalytix#20]
My log fills up with messages from sourceanalytix.
It would be nice if i could disable that.

**Comment by DutchmanNL** [comment]
thank you, my mistake these are loggins related to development and troubleshooting.
i will add an option to the configuration to enable and disable developer logging

**Comment by DutchmanNL** [comment]
fixed in 0.1.9

**Comment by andre1974** [comment]
Problem still exists in 0.1.9
Every 5 seconds i got a log entry.

**Comment by andre1974** [comment]
![screenshot 28](https://user-images.githubusercontent.com/11474126/51431471-7c877600-1c29-11e9-8799-0c94666df817.png)

**Comment by DutchmanNL** [comment]
Not really, you only get a message  when calculations take please. Activate the log and you will see a huge difference :-)

Ibreooen this issue to extend the logging option with basic and advanced

**Comment by DutchmanNL** [comment]
all logging removed in version 0.2.0, state update logging can be enable if wanted :

https://github.com/iobroker-community-adapters/ioBroker.sourceanalytix/releases/tag/0.2.0
